"""Генератор Windows-ресурса версии для PyInstaller (--version-file).

Зачем: exe без VersionInfo («неизвестный файл», ни продукта, ни автора, ни
оригинального имени) — это ровно то, на что охотнее всего ругаются антивирусы и
SmartScreen. Мелочь, которую видно в свойствах файла и в диалоге блокировки, а
нам видно по частоте ложных срабатываний на PyInstaller-сборках.

Версия берётся из `app/version.py` — единственного места, где она живёт
(инвариант HANDOFF §5.13), поэтому рассинхрон «тег / exe / app/version.py»
невозможен в принципе: CI сверяет тег с тем же файлом.

Запуск:
    python tools/make_version_file.py build/version-info.txt
    python tools/make_version_file.py --print
"""
from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "app"))

import version as V                                       # noqa: E402
import windows as W                                       # noqa: E402

W.fix_console()          # русские сообщения в cp1252-консоли иначе роняют скрипт

ASSET = "TarkovBright.exe"          # OriginalFilename: его видит Defender в логах


def quote(text: str) -> str:
    """ASCII + без кавычек внутри: файл читается PyInstaller'ом как Python."""
    out = "".join(ch if 32 <= ord(ch) < 127 else "?" for ch in text)
    return out.replace("\\", "\\\\").replace('"', "'")


def build(version: str, product: str = "TarkovBright") -> str:
    parts = (tuple(list(version_tuple(version)) + [0]))
    strings = [
        ("CompanyName", "markuzewb"),
        ("FileDescription", "TarkovBright - auto gamma for Escape from Tarkov"),
        ("FileVersion", "%s.0" % version),
        ("InternalName", product),
        ("LegalCopyright", "Non-commercial use only; see LICENSE (no warranty)"),
        ("OriginalFilename", ASSET),
        ("ProductName", product),
        ("ProductVersion", version),
    ]
    body = ",\n        ".join("StringStruct('%s', '%s')" % (quote(k), quote(v))
                              for k, v in strings)
    # Сам файл держим в ASCII: PyInstaller читает его локальной кодировкой,
    # а Cyrillic в комментариях превратил бы сборку в UnicodeDecodeError.
    return """# UTF-8
#
# Generated by tools/make_version_file.py from app/version.py.
# Do not edit by hand: CI compares the tag, app/version.py and the built exe.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={fver},
    prodvers={pver},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        {body}
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""".format(fver=parts, pver=parts, body=body)


def version_tuple(text: str) -> tuple:
    nums = []
    for chunk in (text or "0").split(".")[:3]:
        digits = ""
        for ch in chunk:
            if not ch.isdigit():
                break
            digits += ch
        nums.append(int(digits) if digits else 0)
    while len(nums) < 3:
        nums.append(0)
    return tuple(nums)


def main() -> int:
    ap = argparse.ArgumentParser(description="собрать version-info для PyInstaller")
    ap.add_argument("out", nargs="?", help="куда положить (по умолчанию — stdout)")
    ap.add_argument("--version", default=V.__version__,
                    help="версия (по умолчанию берётся из app/version.py)")
    a = ap.parse_args()
    text = build(a.version)
    if a.out:
        os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
        with open(a.out, "w", encoding="ascii", newline="\n") as f:
            f.write(text)
        print("готово: %s (версия %s)" % (a.out, a.version))
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
